/**
 * Shared icon list used by all schemas that expose an icon picker.
 * Single source of truth — import into siteSettings, homePageSettings, etc.
 */
export const iconOptions = [
  {title: 'Balance Scale (policy, justice)', value: 'balance-scale'},
  {title: 'Bicycle (transportation)', value: 'bicycle'},
  {title: 'Book (education)', value: 'book'},
  {title: 'Book Open (curriculum)', value: 'book-open'},
  {title: 'Briefcase (jobs)', value: 'briefcase'},
  {title: 'Bullhorn', value: 'bullhorn'},
  {title: 'Bullseye (priorities)', value: 'bullseye'},
  {title: 'Bus (transit)', value: 'bus'},
  {title: 'Calendar', value: 'calendar'},
  {title: 'Calendar Check (scheduled)', value: 'calendar-check'},
  {title: 'Camera (media)', value: 'camera'},
  {title: 'Chart Bar (metrics)', value: 'chart-bar'},
  {title: 'Chart Line (growth)', value: 'chart-line'},
  {title: 'Chart Pie (budget)', value: 'chart-pie'},
  {title: 'Check Circle (approved)', value: 'check-circle'},
  {title: 'Chalkboard Teacher (schools)', value: 'chalkboard-teacher'},
  {title: 'Clipboard Check (accountability)', value: 'clipboard-check'},
  {title: 'Clock (timelines)', value: 'clock'},
  {title: 'Cloud Sun (energy/weather)', value: 'cloud-sun'},
  {title: 'Coins (funding)', value: 'coins'},
  {title: 'Comment Dots (community input)', value: 'comment-dots'},
  {title: 'Comments (conversation)', value: 'comments'},
  {title: 'Dollar Sign (economy)', value: 'dollar-sign'},
  {title: 'Donate (contribute)', value: 'donate'},
  {title: 'Envelope (contact)', value: 'envelope'},
  {title: 'Exclamation Triangle (alert)', value: 'exclamation-triangle'},
  {title: 'File Alt (documents)', value: 'file-alt'},
  {title: 'Flag (district, civic)', value: 'flag'},
  {title: 'Gavel (legislation)', value: 'gavel'},
  {title: 'Globe Americas (global, trade)', value: 'globe-americas'},
  {title: 'Graduation Cap (higher ed)', value: 'graduation-cap'},
  {title: 'Hammer (construction)', value: 'hammer'},
  {title: 'Hand Holding Heart (care)', value: 'hand-holding-heart'},
  {title: 'Hands Helping', value: 'hands-helping'},
  {title: 'Handshake (partnership)', value: 'handshake'},
  {title: 'Hard Hat (infrastructure)', value: 'hard-hat'},
  {title: 'Heartbeat (health)', value: 'heartbeat'},
  {title: 'Home (housing)', value: 'home'},
  {title: 'Hospital (healthcare)', value: 'hospital'},
  {title: 'Image (gallery)', value: 'image'},
  {title: 'Info Circle (information)', value: 'info-circle'},
  {title: 'Landmark (government)', value: 'landmark'},
  {title: 'Laptop (technology)', value: 'laptop'},
  {title: 'Leaf (environment)', value: 'leaf'},
  {title: 'Lightbulb (ideas)', value: 'lightbulb'},
  {title: 'Map Marker Alt (location)', value: 'map-marker-alt'},
  {title: 'Map Marked Alt (district map)', value: 'map-marked-alt'},
  {title: 'Microphone (speech)', value: 'microphone'},
  {title: 'Newspaper', value: 'newspaper'},
  {title: 'Paw (animal welfare)', value: 'paw'},
  {title: 'Phone (call)', value: 'phone'},
  {title: 'Piggy Bank (savings)', value: 'piggy-bank'},
  {title: 'Play Circle (video play)', value: 'play-circle'},
  {title: 'Podcast (audio)', value: 'podcast'},
  {title: 'Question Circle', value: 'question-circle'},
  {title: 'Receipt (expenses)', value: 'receipt'},
  {title: 'Recycle (sustainability)', value: 'recycle'},
  {title: 'Newspaper (Outline)', value: 'reg-newspaper'},
  {title: 'Road (transport)', value: 'road'},
  {title: 'Route (planning)', value: 'route'},
  {title: 'School (K-12)', value: 'school'},
  {title: 'Shield Alt (public safety)', value: 'shield-alt'},
  {title: 'Solar Panel (clean energy)', value: 'solar-panel'},
  {title: 'Store (small business)', value: 'store'},
  {title: 'Tools (maintenance)', value: 'tools'},
  {title: 'Tree (parks)', value: 'tree'},
  {title: 'Video', value: 'video'},
  {title: 'Vote Yea', value: 'vote-yea'},
  {title: 'Walking (pedestrian)', value: 'walking'},
  {title: 'Water (utilities)', value: 'water'},
  {title: 'Wifi (internet access)', value: 'wifi'},
  {title: 'Wrench (repairs)', value: 'wrench'},
  {title: 'User Friends (families)', value: 'user-friends'},
  {title: 'User Graduate (students)', value: 'user-graduate'},
  {title: 'Users (community)', value: 'users'},
]
