import {
  FaBalanceScale,
  FaBicycle,
  FaBook,
  FaBookOpen,
  FaBriefcase,
  FaBullhorn,
  FaBullseye,
  FaBus,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCamera,
  FaChalkboardTeacher,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheckCircle,
  FaClipboardCheck,
  FaClock,
  FaCloudSun,
  FaCoins,
  FaCommentDots,
  FaComments,
  FaDollarSign,
  FaDonate,
  FaEnvelope,
  FaExclamationTriangle,
  FaFileAlt,
  FaFlag,
  FaGavel,
  FaGlobeAmericas,
  FaGraduationCap,
  FaHammer,
  FaHandHoldingHeart,
  FaHandsHelping,
  FaHandshake,
  FaHardHat,
  FaHeartbeat,
  FaHome,
  FaHospital,
  FaImage,
  FaInfoCircle,
  FaLandmark,
  FaLaptop,
  FaLeaf,
  FaLightbulb,
  FaMapMarkedAlt,
  FaMapMarkerAlt,
  FaMicrophone,
  FaNewspaper,
  FaPaw,
  FaPhone,
  FaPiggyBank,
  FaPlayCircle,
  FaPodcast,
  FaQuestionCircle,
  FaReceipt,
  FaRecycle,
  FaRegNewspaper,
  FaRoad,
  FaRoute,
  FaSchool,
  FaShieldAlt,
  FaSolarPanel,
  FaStore,
  FaTools,
  FaTree,
  FaUserFriends,
  FaUserGraduate,
  FaUsers,
  FaVideo,
  FaVoteYea,
  FaWalking,
  FaWater,
  FaWifi,
  FaWrench,
} from 'react-icons/fa'
import type {IconType} from 'react-icons'

import type {IconName} from './types'

const iconMap: Record<IconName, IconType> = {
  'balance-scale': FaBalanceScale,
  bicycle: FaBicycle,
  book: FaBook,
  'book-open': FaBookOpen,
  briefcase: FaBriefcase,
  bullhorn: FaBullhorn,
  bullseye: FaBullseye,
  bus: FaBus,
  calendar: FaCalendarAlt,
  'calendar-check': FaCalendarCheck,
  camera: FaCamera,
  'chart-bar': FaChartBar,
  'chart-line': FaChartLine,
  'chart-pie': FaChartPie,
  'check-circle': FaCheckCircle,
  'chalkboard-teacher': FaChalkboardTeacher,
  'clipboard-check': FaClipboardCheck,
  clock: FaClock,
  'cloud-sun': FaCloudSun,
  coins: FaCoins,
  'comment-dots': FaCommentDots,
  comments: FaComments,
  'dollar-sign': FaDollarSign,
  donate: FaDonate,
  envelope: FaEnvelope,
  'exclamation-triangle': FaExclamationTriangle,
  'file-alt': FaFileAlt,
  flag: FaFlag,
  gavel: FaGavel,
  'globe-americas': FaGlobeAmericas,
  'graduation-cap': FaGraduationCap,
  hammer: FaHammer,
  'hand-holding-heart': FaHandHoldingHeart,
  'hands-helping': FaHandsHelping,
  handshake: FaHandshake,
  'hard-hat': FaHardHat,
  heartbeat: FaHeartbeat,
  home: FaHome,
  hospital: FaHospital,
  image: FaImage,
  'info-circle': FaInfoCircle,
  landmark: FaLandmark,
  laptop: FaLaptop,
  leaf: FaLeaf,
  lightbulb: FaLightbulb,
  'map-marker-alt': FaMapMarkerAlt,
  'map-marked-alt': FaMapMarkedAlt,
  microphone: FaMicrophone,
  newspaper: FaNewspaper,
  paw: FaPaw,
  phone: FaPhone,
  'piggy-bank': FaPiggyBank,
  'play-circle': FaPlayCircle,
  podcast: FaPodcast,
  'question-circle': FaQuestionCircle,
  receipt: FaReceipt,
  recycle: FaRecycle,
  'reg-newspaper': FaRegNewspaper,
  road: FaRoad,
  route: FaRoute,
  school: FaSchool,
  'shield-alt': FaShieldAlt,
  'solar-panel': FaSolarPanel,
  store: FaStore,
  tools: FaTools,
  tree: FaTree,
  'user-friends': FaUserFriends,
  'user-graduate': FaUserGraduate,
  users: FaUsers,
  video: FaVideo,
  'vote-yea': FaVoteYea,
  walking: FaWalking,
  water: FaWater,
  wifi: FaWifi,
  wrench: FaWrench,
}

export function resolveCmsIcon(icon: IconName | undefined, fallback: IconType): IconType {
  if (!icon) {
    return fallback
  }

  return iconMap[icon] ?? fallback
}
